### ISSUE TITLE
Update sqlite3 package

### ISSUE THREAD

**Issue by adityapatadia** [lukechilds/keyv-sqlite#39]
sqlite3 version `4.0.2` is released and it's easier to install. Please upgrade package to support it. It also brings support for Node v10

**Comment by lukechilds** [comment]
Resolved in https://github.com/lukechilds/keyv-sqlite/pull/40

**Comment by recapitalverb** [comment]
sqlite3 version `4.0.6` is now released. Please upgrade the package to support it - some users are having problems with installing previous versions of sqlite3 ie. `4.0.2`. Thank you.

**Comment by Dimensional** [comment]
I have to agree. I'm unable to compile sqlite3@4.0.2 because it no longer exists for download from the location keyv is going to.
