### ISSUE TITLE
How to connect to a remote SQL

### ISSUE THREAD

**Issue by almostStatic** [lukechilds/keyv-sqlite#52]
I've got a remote SQL Database as part of my domain (cPanel), I've added a username and password but I'm not able to connect to that database via keyv. Below is everything I've tried: 

```js
client.db = new keyv("sqlite://http://{IP}/", { host: "{ID}", user: 'admin', password: process.env.DB_PASSWORD, database: "test" })
```

Everything is configured on cPanel, I'm just not sure how to connect to that remote SQL DB via keyv...

**Comment by lukechilds** [comment]
`keyv-sqlite` is for interfacing with an SQLite database. Sounds like you have a different hosted database. Try the Postgres or MySQL adapter.
