### ISSUE TITLE
Suggestion: Add <Keyv>.getAll()

### ISSUE THREAD

**Issue by almostStatic** [lukechilds/keyv-sqlite#53]
You should add another method: 
`KeyvInstance.getAll();`
return all key-value pairs 
ex.
```js
Keyv.getAll();
```
Output:
```js

[
    { key: 'foo', value: 'bar', expires: null }
]
```

**Comment by jaredwray** [comment]
@almostStatic thanks so much for the suggestion but because of all the storage adapters we support (https://github.com/lukechilds/keyv#official-storage-adapters) it would be hard to support this feature across all of them. 

That is why we have stayed with the `Map` construct and capabilities.
